---
- hosts: localhost
  gather_facts: True
  connection: local
  user: remote

  vars:
    - config: "/opt/variables/oneview_config.json"    
  tasks:
     - name: Creates directory
       file: path=/tmp/www1 state=directory mode=0775
     - name: Gather facts about all Storage Volume Templates
       oneview_storage_volume_template_facts:
         config: "{{ config }}"
#      delegate_to: localhost
#    - debug: var=storage_volume_templates
