---
- hosts: all
  gather_facts: True
  connection: local
  user: remote
  tasks:
    - name: Gather facts about all Connection Templates
      oneview_connection_template_facts:
      delegate_to: localhost
