---
- hosts: localhost
  gather_facts: True
  connection: local
  user: remote

  vars:
    - config: "/opt/variables/oneview_config.json"  
  environment:
    ANSIBLE_LIBRARY: "/usr/lib/python2.7/site-packages/hpOneView/oneview-ansible/library"
    PYTHONPATH: "/usr/lib/python2.7/site-packages/hpOneView/oneview-ansible/library"
  
  tasks:
#     - name: Creates directory
#       file: path=/tmp/www1 state=directory mode=0775
     - name: Create a Server Profile with connections
       oneview_server_profile:
         config: "{{ config }}"
         data:
           name: server-profile-with-connections
           connections:
             - id: 1
               name: connection1
               functionType: Ethernet
               portId: Auto
               requestedMbps: 2500
               networkName: eth-demo
#     delegate_to: localhost
