---
- hosts: localhost
  gather_facts: True
  connection: local
  user: remote

  vars:
    ip: '10.0.5.2'    
#   username: 'username'
#   password: 'password'

  tasks:
    - name: Gather facts about all Storage Volume Templates
      oneview_storage_volume_template_facts:
      config: "{{ config }}"
      delegate_to: localhost

    - debug: var=storage_volume_templates
